{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.string.plugin",
    "module": "stringblur",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "stringblur-1.1.2.jar",
          "url": "stringblur-1.1.2.jar",
          "size": 59449,
          "sha512": "cb06c8e69890a65cda51863cba0f1929cfc90c59f2d577505dbb023119292eed81c887b5c72581686f58a73b63d6fc607d499868ebcd938221969b061ce2367f",
          "sha256": "d382ceb5fe6f8abd526337b100ce0c9f387b895176218350f93fd2951cb75eeb",
          "sha1": "8f5cb1dc808215b623194379717d45332f5ef690",
          "md5": "9b1f119422262327d9b013288b827c8a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "com.squareup",
          "module": "javawriter",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "stringblur-1.1.2.jar",
          "url": "stringblur-1.1.2.jar",
          "size": 59449,
          "sha512": "cb06c8e69890a65cda51863cba0f1929cfc90c59f2d577505dbb023119292eed81c887b5c72581686f58a73b63d6fc607d499868ebcd938221969b061ce2367f",
          "sha256": "d382ceb5fe6f8abd526337b100ce0c9f387b895176218350f93fd2951cb75eeb",
          "sha1": "8f5cb1dc808215b623194379717d45332f5ef690",
          "md5": "9b1f119422262327d9b013288b827c8a"
        }
      ]
    }
  ]
}
