{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bytedance.android",
    "module": "aabresguard-plugin",
    "version": "0.1.16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.bytedance.android",
          "module": "aabresguard-core",
          "version": {
            "requires": "0.1.16"
          },
          "excludes": [
            {
              "group": "com.android.tools.build",
              "module": "bundletool"
            },
            {
              "group": "com.google.guava",
              "module": "guava"
            },
            {
              "group": "com.android.tools.build",
              "module": "gradle"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "aabresguard-plugin-0.1.16.jar",
          "url": "aabresguard-plugin-0.1.16.jar",
          "size": 19694,
          "sha512": "7a5de0233fcd7a83af72e0b9b1c915ad27a690d0fbbf84bad81c2fab5da10cd8eb7c193ff4e864cd935eb037f71c9fabb2ed05320175b5a72281c3ddfa6e4547",
          "sha256": "014532414199b0d51668272e47025ba2062bef34aec5d811a5c05e92beb00cd5",
          "sha1": "ce724c02454677a2737bbffda96f13af5654ecce",
          "md5": "b6177c8054642be43ff1489d2306c105"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "2.0.21"
          },
          "excludes": [
            {
              "group": "com.android.tools.build",
              "module": "bundletool"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.0.21"
          },
          "excludes": [
            {
              "group": "com.android.tools.build",
              "module": "bundletool"
            }
          ]
        },
        {
          "group": "com.bytedance.android",
          "module": "aabresguard-core",
          "version": {
            "requires": "0.1.16"
          },
          "excludes": [
            {
              "group": "com.android.tools.build",
              "module": "bundletool"
            },
            {
              "group": "com.google.guava",
              "module": "guava"
            },
            {
              "group": "com.android.tools.build",
              "module": "gradle"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "aabresguard-plugin-0.1.16.jar",
          "url": "aabresguard-plugin-0.1.16.jar",
          "size": 19694,
          "sha512": "7a5de0233fcd7a83af72e0b9b1c915ad27a690d0fbbf84bad81c2fab5da10cd8eb7c193ff4e864cd935eb037f71c9fabb2ed05320175b5a72281c3ddfa6e4547",
          "sha256": "014532414199b0d51668272e47025ba2062bef34aec5d811a5c05e92beb00cd5",
          "sha1": "ce724c02454677a2737bbffda96f13af5654ecce",
          "md5": "b6177c8054642be43ff1489d2306c105"
        }
      ]
    }
  ]
}
