{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.string.plugin",
    "module": "stringblur",
    "version": "1.1.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "stringblur-1.1.5.jar",
          "url": "stringblur-1.1.5.jar",
          "size": 52960,
          "sha512": "dd0ec56a04b14ba06328744689decaf683bb470e9838cc2340fdc9bf41e3803d542a7761fc8a659d88c81db629e51f94435ce0b3fb79a815156539d7c8a84a8f",
          "sha256": "0d89a7fb185bb6005ecb349149b31b5c031421e69077d4dce62b793de8dc0557",
          "sha1": "63c0520fd0097dc86cf43ded3c1c9fa2ef62070f",
          "md5": "9c84601e85b5255fcd96102e079a4019"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.8"
          }
        },
        {
          "group": "com.squareup",
          "module": "javawriter",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "com.android.string.plugin",
          "module": "common",
          "version": {
            "requires": "1.1.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "stringblur-1.1.5.jar",
          "url": "stringblur-1.1.5.jar",
          "size": 52960,
          "sha512": "dd0ec56a04b14ba06328744689decaf683bb470e9838cc2340fdc9bf41e3803d542a7761fc8a659d88c81db629e51f94435ce0b3fb79a815156539d7c8a84a8f",
          "sha256": "0d89a7fb185bb6005ecb349149b31b5c031421e69077d4dce62b793de8dc0557",
          "sha1": "63c0520fd0097dc86cf43ded3c1c9fa2ef62070f",
          "md5": "9c84601e85b5255fcd96102e079a4019"
        }
      ]
    }
  ]
}
