{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.string.plugin",
    "module": "stringblur",
    "version": "1.1.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "stringblur-1.1.6.jar",
          "url": "stringblur-1.1.6.jar",
          "size": 57736,
          "sha512": "0463b321473b2fe34923ac13b4ac9c689937054a0406f9762c4afa31c508d4d53c2bcc8519f68f2a2c59970e8480fc30d5c460fbd82a696678812dd05101c80a",
          "sha256": "78023950292b20e948e65fdcff87de95f962502a77409bea12fcfafae1c670a3",
          "sha1": "29aa93c246c43111ab8f04a69e4dbd174a3f47cd",
          "md5": "405af7af5d7519bfff09626816e82e06"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.8"
          }
        },
        {
          "group": "com.squareup",
          "module": "javawriter",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "com.android.string.plugin",
          "module": "common",
          "version": {
            "requires": "1.1.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "stringblur-1.1.6.jar",
          "url": "stringblur-1.1.6.jar",
          "size": 57736,
          "sha512": "0463b321473b2fe34923ac13b4ac9c689937054a0406f9762c4afa31c508d4d53c2bcc8519f68f2a2c59970e8480fc30d5c460fbd82a696678812dd05101c80a",
          "sha256": "78023950292b20e948e65fdcff87de95f962502a77409bea12fcfafae1c670a3",
          "sha1": "29aa93c246c43111ab8f04a69e4dbd174a3f47cd",
          "md5": "405af7af5d7519bfff09626816e82e06"
        }
      ]
    }
  ]
}
