{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bytedance.android",
    "module": "aabresguard-plugin",
    "version": "0.1.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.bytedance.android",
          "module": "aabresguard-core",
          "version": {
            "requires": "0.1.12"
          },
          "excludes": [
            {
              "group": "com.android.tools.build",
              "module": "bundletool"
            },
            {
              "group": "com.google.guava",
              "module": "guava"
            },
            {
              "group": "com.android.tools.build",
              "module": "gradle"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "aabresguard-plugin-0.1.12.jar",
          "url": "aabresguard-plugin-0.1.12.jar",
          "size": 19262,
          "sha512": "f5a56764db0252cad127d50043bce3e2088a55c5d54d7f1fa7172f026cfad461d54b9ed5aafad2d3801cc2f2c43ac7ac4470ceb42431c7df6b87437cf52b501a",
          "sha256": "034f252048f10b698778eac031b9700f7be802f21c12cb665b43630cd4072690",
          "sha1": "226aec0cc46e6a05fe850c5e64a46c319e6c1cfa",
          "md5": "fb75657d23e0dad889ec06075a31ca2b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "2.0.21"
          },
          "excludes": [
            {
              "group": "com.android.tools.build",
              "module": "bundletool"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.0.21"
          },
          "excludes": [
            {
              "group": "com.android.tools.build",
              "module": "bundletool"
            }
          ]
        },
        {
          "group": "com.bytedance.android",
          "module": "aabresguard-core",
          "version": {
            "requires": "0.1.12"
          },
          "excludes": [
            {
              "group": "com.android.tools.build",
              "module": "bundletool"
            },
            {
              "group": "com.google.guava",
              "module": "guava"
            },
            {
              "group": "com.android.tools.build",
              "module": "gradle"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "aabresguard-plugin-0.1.12.jar",
          "url": "aabresguard-plugin-0.1.12.jar",
          "size": 19262,
          "sha512": "f5a56764db0252cad127d50043bce3e2088a55c5d54d7f1fa7172f026cfad461d54b9ed5aafad2d3801cc2f2c43ac7ac4470ceb42431c7df6b87437cf52b501a",
          "sha256": "034f252048f10b698778eac031b9700f7be802f21c12cb665b43630cd4072690",
          "sha1": "226aec0cc46e6a05fe850c5e64a46c319e6c1cfa",
          "md5": "fb75657d23e0dad889ec06075a31ca2b"
        }
      ]
    }
  ]
}
