{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.string.plugin",
    "module": "stringblur",
    "version": "1.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "stringblur-1.1.3.jar",
          "url": "stringblur-1.1.3.jar",
          "size": 59384,
          "sha512": "cefa9a75e89f3e2315b890b480b8da8406ee1822d14e357c3df6c1f27b547829793e2206359792c22a11c01d9ce89928443cc9c1e3848ecab1b1bd30bae9fe64",
          "sha256": "2f8d285f2f363173ca0da8d084777150b287aa67a6c5868e3b4031f754ac7e20",
          "sha1": "484c4262dc6bc5daaa76765b64f55aae0593158a",
          "md5": "645e2e42721b9a2c8e28ed4fe5e2a1cd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "com.squareup",
          "module": "javawriter",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "stringblur-1.1.3.jar",
          "url": "stringblur-1.1.3.jar",
          "size": 59384,
          "sha512": "cefa9a75e89f3e2315b890b480b8da8406ee1822d14e357c3df6c1f27b547829793e2206359792c22a11c01d9ce89928443cc9c1e3848ecab1b1bd30bae9fe64",
          "sha256": "2f8d285f2f363173ca0da8d084777150b287aa67a6c5868e3b4031f754ac7e20",
          "sha1": "484c4262dc6bc5daaa76765b64f55aae0593158a",
          "md5": "645e2e42721b9a2c8e28ed4fe5e2a1cd"
        }
      ]
    }
  ]
}
