{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.string.plugin",
    "module": "stringblur",
    "version": "1.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "stringblur-1.1.1.jar",
          "url": "stringblur-1.1.1.jar",
          "size": 59215,
          "sha512": "d5b0517060a69d33c05b12784678c281ce0fbac44f17f981f4fbe60137bec9d42087e406fb1a94e44ad3a235527c803a40abdb433a3ae9185146433774a009ce",
          "sha256": "7cb183a35b519581dcc83ff2cc0ebfd887b981386790a91a019ef6197d8e57de",
          "sha1": "790771e3ffd2befce0e577b01038168926a2662b",
          "md5": "579ae615751cb6dda12dfdafc434d0d6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.5"
          }
        },
        {
          "group": "com.squareup",
          "module": "javawriter",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "stringblur-1.1.1.jar",
          "url": "stringblur-1.1.1.jar",
          "size": 59215,
          "sha512": "d5b0517060a69d33c05b12784678c281ce0fbac44f17f981f4fbe60137bec9d42087e406fb1a94e44ad3a235527c803a40abdb433a3ae9185146433774a009ce",
          "sha256": "7cb183a35b519581dcc83ff2cc0ebfd887b981386790a91a019ef6197d8e57de",
          "sha1": "790771e3ffd2befce0e577b01038168926a2662b",
          "md5": "579ae615751cb6dda12dfdafc434d0d6"
        }
      ]
    }
  ]
}
