{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bytedance.android",
    "module": "aabresguard-plugin",
    "version": "0.1.17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.bytedance.android",
          "module": "aabresguard-core",
          "version": {
            "requires": "0.1.17"
          },
          "excludes": [
            {
              "group": "com.android.tools.build",
              "module": "bundletool"
            },
            {
              "group": "com.google.guava",
              "module": "guava"
            },
            {
              "group": "com.android.tools.build",
              "module": "gradle"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "aabresguard-plugin-0.1.17.jar",
          "url": "aabresguard-plugin-0.1.17.jar",
          "size": 21921,
          "sha512": "3d54c6719d81f8f7b0d01dba434ee3839e3856e2c8158454a1db6cd62031f57ecc1196023111c9a485a92b7e2be21fbae98a55b5b906c5220c7aaf131c5a49c7",
          "sha256": "9952afdaa88f09e7759cbd165c1f42099eefec7374b0bd29bfbeb41033163306",
          "sha1": "8cb23fbe4a251725f65ad54112105cc0d66acf53",
          "md5": "8033961e88cfeaa623abd86469a28e27"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "2.0.21"
          },
          "excludes": [
            {
              "group": "com.android.tools.build",
              "module": "bundletool"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.0.21"
          },
          "excludes": [
            {
              "group": "com.android.tools.build",
              "module": "bundletool"
            }
          ]
        },
        {
          "group": "com.bytedance.android",
          "module": "aabresguard-core",
          "version": {
            "requires": "0.1.17"
          },
          "excludes": [
            {
              "group": "com.android.tools.build",
              "module": "bundletool"
            },
            {
              "group": "com.google.guava",
              "module": "guava"
            },
            {
              "group": "com.android.tools.build",
              "module": "gradle"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "aabresguard-plugin-0.1.17.jar",
          "url": "aabresguard-plugin-0.1.17.jar",
          "size": 21921,
          "sha512": "3d54c6719d81f8f7b0d01dba434ee3839e3856e2c8158454a1db6cd62031f57ecc1196023111c9a485a92b7e2be21fbae98a55b5b906c5220c7aaf131c5a49c7",
          "sha256": "9952afdaa88f09e7759cbd165c1f42099eefec7374b0bd29bfbeb41033163306",
          "sha1": "8cb23fbe4a251725f65ad54112105cc0d66acf53",
          "md5": "8033961e88cfeaa623abd86469a28e27"
        }
      ]
    }
  ]
}
