{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bytedance.android",
    "module": "aabresguard-plugin",
    "version": "0.1.18",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.bytedance.android",
          "module": "aabresguard-core",
          "version": {
            "requires": "0.1.18"
          },
          "excludes": [
            {
              "group": "com.android.tools.build",
              "module": "bundletool"
            },
            {
              "group": "com.google.guava",
              "module": "guava"
            },
            {
              "group": "com.android.tools.build",
              "module": "gradle"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "aabresguard-plugin-0.1.18.jar",
          "url": "aabresguard-plugin-0.1.18.jar",
          "size": 23255,
          "sha512": "8b866f1e4033226343662bbd5535154ce700fc69da3946933ca01a6bfa7823800569a868deca9e2a96329121ada418e10bd99179a33ade5257ba13588a1b1c7c",
          "sha256": "adb28757cbbf36cb5e9e43d4ad260463580b6ea629b59ba5158eb56fc9e0f050",
          "sha1": "deb282344aa6ffbe46cab9cfe5fc9de54d75bed2",
          "md5": "dfc3b917528cf4dd18f4e235f9f65cd7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "2.0.21"
          },
          "excludes": [
            {
              "group": "com.android.tools.build",
              "module": "bundletool"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.0.21"
          },
          "excludes": [
            {
              "group": "com.android.tools.build",
              "module": "bundletool"
            }
          ]
        },
        {
          "group": "com.bytedance.android",
          "module": "aabresguard-core",
          "version": {
            "requires": "0.1.18"
          },
          "excludes": [
            {
              "group": "com.android.tools.build",
              "module": "bundletool"
            },
            {
              "group": "com.google.guava",
              "module": "guava"
            },
            {
              "group": "com.android.tools.build",
              "module": "gradle"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "aabresguard-plugin-0.1.18.jar",
          "url": "aabresguard-plugin-0.1.18.jar",
          "size": 23255,
          "sha512": "8b866f1e4033226343662bbd5535154ce700fc69da3946933ca01a6bfa7823800569a868deca9e2a96329121ada418e10bd99179a33ade5257ba13588a1b1c7c",
          "sha256": "adb28757cbbf36cb5e9e43d4ad260463580b6ea629b59ba5158eb56fc9e0f050",
          "sha1": "deb282344aa6ffbe46cab9cfe5fc9de54d75bed2",
          "md5": "dfc3b917528cf4dd18f4e235f9f65cd7"
        }
      ]
    }
  ]
}
